---
bootstrap_url: http://172.17.8.100
cluster_name: 'dcos-vagrant'
exhibitor_storage_backend: static
ip_detect_filename: /genconf/ip-detect
master_discovery: static
master_list:
- 172.17.8.101
resolvers:
- 8.8.8.8
